### ISSUE TITLE
Unable to set Processor

### ISSUE THREAD

**Issue by warmy54** [nkast/Aether.Extras#1]
Was trying to install the library to test it. 
I did the instructions in the wiki 
here: [https://github.com/jmgraeffe/monogame-3d-animation-tutorial/wiki/Adding-library-to-existing-project#add-aetheranimation-li[…]-windowssharpdx-project](https://github.com/jmgraeffe/monogame-3d-animation-tutorial/wiki/Adding-library-to-existing-project#add-aetheranimation-library-to-existing-monogame-windowssharpdx-project) 

But when trying to set the processor for a test fbx file, the aeather lib ones are not available. Only the base GameLab options

**Comment by nkast** [comment]
This seems related to https://github.com/nkast/Aether.Extras/issues/2.

The link you provided probably used MG 3.7 or earlier. With 3.8.0 and 3.8.1 they progressively dropped support for .NetFramework 4 an Netstandard 2.0, and with all the unresolved issues that come with it I could not see a working path on how I could still support it.

**Comment by nkast** [comment]
Since v1.1.0 the library migrated to KNI framework.

Anyone that need to target MonoGame will have to use v1.0.0. 
Or to build the library from source will the necessary changes.
